### ISSUE TITLE
Kompatibilität mit pjax

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/structure_tweaks#1]
Um die aktuellen Kategorien per PHP abfragen zu können wird Pjax in der Strukturansicht deaktiviert. Besser wäre es, wenn die gewählten Kategorien an JavaScript übergeben werden.

**Comment by gharlan** [comment]
Eigentlich sind es bei PJAX die selben URLs wie ohne. Es sollten also alle Parameter abfragbar sein.

**Comment by DanielWeitenauer** [comment]
Ich hatte auf die Schnelle die Redaxo 4 Variante benutzt, in der es über PHP geregelt wurde. Jetzt läuft es auch mit PJAX.
