### ISSUE TITLE
Keine Anzeige des Kategorietrenners bei Navigation über die Quick Navigation

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/structure_tweaks#13]
Daniel:
> Ich muss mal schauen, welcher Event von Quicknavigation getriggert wird.

Hinweis von Thomas Skerbis:
> Quick Navigation schaut nach pjax:ready ... in der Github Version schon rex:ready

**Comment by DanielWeitenauer** [comment]
Das Problem scheint mit diesem Parameter in der quick_navigation zusammenzuhängen:
https://github.com/FriendsOfREDAXO/quick_navigation/blob/master/lib/QuickNavigation.php#L75
nehme ich ihn raus, funktioniert es. Ich kann allerdings nicht sagen, wozu der Parameter benötigt wird. @skerbis Weißt du da mehr?

**Comment by DanielWeitenauer** [comment]
Ah, habs raus. REDAXO übernimmt die article_id aus der URL in die Links. Momentan setzt structure_tweaks die id immer auf 0.

**Comment by DanielWeitenauer** [comment]
Gelöst: https://github.com/FriendsOfREDAXO/structure_tweaks/commit/0f14e66d83175f73f168bdbdaca481e2601890b6

**Comment by skerbis** [comment]
Muss ich noch was machen?

**Comment by DanielWeitenauer** [comment]
Ich hab es lösen können. Jetzt funktioniert es richtig, daher brauchst du nichts tun. Danke dir!
