### ISSUE TITLE
3. Status ausblenden

### ISSUE THREAD

**Issue by RexDude** [FriendsOfREDAXO/structure_tweaks#2]
Hi!
Cool meine 2 Babys sind hier gelandet :)
Hätte noch ein drittes was ich sehr gut brauchen könnt und zwar den Status einer Kategorie und/oder eines Artikels verstecken. Manche Kats/Arts sind lediglich als Container gedacht und sollen immer offline (oder evtl. auch online) bleiben. Ein Redaktuer sollte hier deshalb aufkeinen Fall herumspielen (was ich schon mal erlebt habe). Damit hätte man dann "echte" Containers ohne Startartikel und ohne Status und sauber getrennt vom restlichen Content :)

**Comment by DanielWeitenauer** [comment]
Welche Einstellungsoption wäre dafür am sinnvollsten? 
Eine Einstellung "Container", die den Startartikel und die Status/Funktionen deaktiviert oder zwei getrennte Einstellungen "Startartikel ausblenden" und "Funktionen ausblenden"? Wahrscheinlich wird das nur in Kombination gebraucht, oder?

**Comment by RexDude** [comment]
hey ja gute frage. theoretisch würde die container sache ausreichen. blendet: startartikel, status und eigentlich ja auch ändern und löschen aus.
und startartikel ausblenden bleibt ja eh auch extra bestehen falls man dass ohne container doch auch mal brauchen sollt.

**Comment by DanielWeitenauer** [comment]
Ich habe das jetzt doch erst einmal als eigenständige Funktion eingebaut. Die Funktion ändern blende ich nicht aus, da sonst die Meta-Daten nicht erreichbar wären.  https://github.com/FriendsOfREDAXO/structure_tweaks/commit/0378b0cc583a1b17efb34e5484c2b2c5c3cf0ce5

**Comment by RexDude** [comment]
Danke erstmal für deine Mühen!
Finde die Lösung allerdings nichts halbes und nichts ganzes. Könntest du bitte in die betreffende TR eine Klasse hinzufügen. Dann kann ich den Rest nach meinem Geschmack anpassen. Z.B. weiss ich auch nicht ob ich mich an die Bindestriche gewöhnen will ;)

**Comment by DanielWeitenauer** [comment]
Was stört dich und was schlägst du vor?

**Comment by DanielWeitenauer** [comment]
Soll die Zeile insgesamt anders dargestellt werden?

**Comment by RexDude** [comment]
Hmm also ich würd entweder lediglich nur den Status ausblenden (= "Status ausblenden" im Addon) oder alle (!) Funktionen (= "Funktionen ausblenden" im Addon). Ich tendiere sogar jetzt nur zum ersteren...wenn der Kunde diese Katageorien löscht hat er halt Pech (und hoffentlich ein Backup :)) Mit Status ausblenden und Startartikel verstcken bekomme ich dann meine Conatiner gut hin :)

**Comment by RexDude** [comment]
Geht das? Also nur Status ausblenden?

**Comment by DanielWeitenauer** [comment]
Ich habe es noch einmal angepasst. Der Status wird nun ausgeblendet. Außerdem erhalten alle Funktionen und die Tabellenzeile eigene CSS-Klassen. Bei Bedarf kann das Ausblenden der Funktionen so individualisiert werden.

**Comment by RexDude** [comment]
Toll! Vielen Dank!!!

**Comment by RexDude** [comment]
@DanielWeitenauer 

Hab noch paar Vorschläge:
- Funktion sollte jetzt "Status verstecken heissen"
- Anstatt verstecken würd ich es doch lieber disablen (wie REDAXO dass macht beim "löschen" Link bei den Startartikeln)
- Das ganze wäre cool auch für normale Artikel (aktuell geht nur Kategorien). Die Idee kommt aus nem realen UseCase.
- Und wenns disabled wird sollte dann die Funktion "Status deaktivieren" heissen ;)
