### ISSUE TITLE
Umlaut-Problem bei Metadaten

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/structure_tweaks#34]
![image001](https://user-images.githubusercontent.com/791247/37711800-3a317276-2d12-11e8-9088-47d01838aa02.png)

**Comment by DanielWeitenauer** [comment]
Diesen Fehler kann ich nicht nachvollziehen. Bei mir wird der März als Mrz. abgekürzt. 
Da das Datum über `rex_formatter::strftime` formatiert wird, könnte es an deinen Lokalisierungseinstellungen liegen. Hast du hier etwas spezielles eingestellt? Welche PHP-Version ist nutzt du?

**Comment by skerbis** [comment]
Nutze 7.2 locals sind installiert

**Comment by DanielWeitenauer** [comment]
Seltsam, ich kann den Fehler nur provozieren, wenn ich bewusst falsche Daten mit setlocale() setze. Tritt der Fehler tatsächlich nur auf, wenn die Metainfos in die Seitenspalte verschoben werden?

**Comment by skerbis** [comment]
hab das Problem gefunden. Alles ok bei Dir. Eine eingebundene Class hat die locals überschrieben
Dennoch Danke für Deine Mühen.
