### ISSUE TITLE
Metainfos Sidebar vs. WYSIWYG

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/structure_tweaks#44]
Ist die Funktion aktiviert, dass die Metas in der Sidebar dargestellt werden, duplizieren sich bei der Bearbeitung im Hauptbereich WYSIWYG-Editroren in den Metas. 
Getestet mit redactor und cke5

![bildschirmfoto 2018-10-29 um 11 00 05](https://user-images.githubusercontent.com/791247/47643877-fea55880-db6c-11e8-9b8f-6afcc6551e7b.png)

**Comment by DanielWeitenauer** [comment]
Da kann ich hier wenig machen. Die Editor-Addons packen bei einem rex:ready ihr JavaScript auf jede Textarea, die sie finden können. Dort müsste geprüft werden, ob bereits eine Editor-Instanz für die Textarea existiert.

**Comment by skerbis** [comment]
ist im nächsten cke5 gefixt.

**Comment by skerbis** [comment]
stimmt kein Problem in diesem AddOn, es muss bei den Editoren berücksichtigt werden
