### ISSUE TITLE
Problem mit neuer Redaxo 5.7.0-beta1

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/structure_tweaks#47]
Die Funktion, die Metadaten in der Seitenspalte anzeigen zu lassen, klappt mit der Redaxo 5.7-beta nicht mehr. Ich lege auch ein Issue dort an, da ich nicht weiß, auf welcher Seite Anpassungen gemacht werden sollten.

**Comment by skerbis** [comment]
der Fehler liegt im Core und sollte dort korrigiert werden: 
https://github.com/redaxo/redaxo/issues/2372#issuecomment-450736100
