### ISSUE TITLE
Backend - Layout von Modulen und Templates

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/structure_tweaks#51]
Hallo zusammen,
bei kleineren Monitoren (ich mache Webdesign noch auf 1280 x 1024 ;-) stoße ich im Backend immer auf eine Sache, deren Änderung ich mir wünschen würde. Bei den Modulen und bei den Templates wird durch die Zweispaltigkeit soviel Platz verschwendet. Lassen sich nicht in Zukunft besser die Label-ths oberhalb der Eingabefelder ansiedeln? Dann wäre mehr Platz für die Eingabe. Viele Grüße v. Heinz

**Comment by DanielWeitenauer** [comment]
Hi, meinst du die Formulare der Seiten "Module" und "Templates"? In dem Fall scheint es mir sinnvoller, die deinen Änderungswunsch direkt im REDAXO-Core anzubringen, da es eine eher überschaubare Änderung ist. structure_tweaks ist eher für Anpassungen gedacht, die sich aktuell noch nicht problemlos im Core integrieren lassen.
Auf die Schnelle könntest du auch einfach eigene CSS-Styles ins Backend einbinden, um den Mobile-Breakpoint anzupassen.

**Comment by erraiva** [comment]
Danke Daniel, hast du einen Link wo ich die Issues für den Core finde? LG Heinz

**Comment by DanielWeitenauer** [comment]
https://github.com/redaxo/redaxo/issues/2753
