### ISSUE TITLE
metainfos in eigne unterseite verschieben

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/structure_tweaks#60]
ab redaxo 5.10 sind die metainfos in der rechten seitenspalte. das kann bei grosszügigem einsatz schnell sehr unübersichtlich werden.
ein optionale verschiebung zurück in eine eigene seite wäre super...
hier gibt es eine diskussion dazu:
https://github.com/redaxo/redaxo/issues/3481

**Comment by skerbis** [comment]
Den Weg zurück zur alten Darstellung empfinde ich als keine Verbesserung. Man sollte über Lösungen nachdenken bestimmte Metas erst on click zu zeigen / aufzuklappen.
