### ISSUE TITLE
Fehler bei Installation des Addons (rex_exception)

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/structure_tweaks#73]
Beim Versuch der Installation der aktuellsten Version in eine bestehende Redaxo-Installation kommt folgender Fehler bei mir:

**rex_exception:** Table "rex_structure_tweaks" does not exist.
**File:** redaxo/src/core/lib/sql/table.php
**Line:** 751

<details>
<summary>Stacktrace</summary>

| Function                     | File                                            | Line     |
| ---------------------------- | ----------------------------------------------- | -------- |
| rex_sql_table->alter         | redaxo/src/addons/structure_tweaks/install.php  | 12       |
| include                      | redaxo/src/core/lib/packages/package.php        | 250      |
| rex_package->includeFile     | redaxo/src/core/lib/packages/manager.php        | 142      |
| rex_package_manager->install | redaxo/src/core/lib/packages/addons/manager.php | 27       |
| rex_addon_manager->install   | redaxo/src/core/lib/packages/api_package.php    | 34       |
| rex_api_package->execute     | redaxo/src/core/lib/api_function.php            | 179      |
| rex_api_function::handleCall | redaxo/src/core/backend.php                     | 231      |
| require                      | redaxo/src/core/boot.php                        | 137      |
| require                      | redaxo/index.php                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.11.0, PHP 7.3.11, MariaDB 10.1.41)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.11.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.11     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MariaDB 10.1.41                |
| Character set | utf8                           |
|       Warning | Die verwendete MariaDB Version 10.1.41 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Server        |               |
| ------------: | :------------ |
|            OS | Linux         |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.25 |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/86.0.4240.111 |
|      Protocol | HTTP/1.1             |
|         HTTPS | yes                  |

| Packages                |             |
| ----------------------: | :---------- |
|                 adminer | 1.8.1       |
|                  backup | 2.6.1       |
|                be_style | 2.11.0      |
|         be_style/redaxo | 2.11.0      |
|                be_tools | 1.5.2       |
|                 bloecks | 3.0.0       |
|        bloecks/cutncopy | 3.0.0       |
|          bloecks/status | 3.0.0       |
|            cameraslider | 1.0         |
|              cheatsheet | 0.0.1       |
|                ckeditor | 4.13.1      |
|                 cronjob | 2.7.1       |
|  cronjob/article_status | 2.7.1       |
| cronjob/optimize_tables | 2.7.1       |
|                 cropper | 1.1.0       |
|               developer | 3.9.0       |
|         emailobfuscator | 3.0.0       |
|              hp_seometa | 1.1.3       |
|                 install | 2.8.0       |
|                    iwcc | 2.0.0-beta8 |
|            jqlightboxes | 1.0         |
|             maintenance | 2.4.1       |
|           massif_minify | 1.3.0       |
|           media_manager | 2.10.0      |
|               mediapool | 2.9.0       |
|                metainfo | 2.7.2       |
|       parameter_rewrite | 1.0.0       |
|               phpmailer | 2.9.0       |
|                 project | dev         |
|        quick_navigation | 3.9.3       |
|               search_it | 6.7.3       |
| search_it/documentation | 6.7.3       |
|     search_it/plaintext | 6.7.3       |
|         search_it/stats | 6.7.3       |
|              seocheckup | 1.3.5       |
|             simplestats | 1.0.0       |
|               structure | 2.11.0      |
|       structure/content | 2.11.0      |
|       structure/history | 2.11.0      |
|       structure/version | 2.11.0      |
|                uploader | 2.2.0       |
|                   users | 2.7.0       |
|                   yform | 3.4.1       |
|              yform/docs | 3.3.1       |
|             yform/email | 3.4.1       |
|           yform/manager | 3.4.1       |
|                yrewrite | 2.7         |

</details>

**Comment by DanielWeitenauer** [comment]
Das ist in der GitHub-Version bereits korrigiert, aber noch nicht veröffentlicht. Kannst du mal prüfen, ob es damit auch bei dir klappt?

**Comment by iceman-fx** [comment]
Soeben mit der Github Version getestet ... funktioniert ohne Fehler.

**Comment by dpf-dd** [comment]
Das Problem ist bei der Version 1.3.0beta im Redaxo-Installer nach wie vor reproduzierbar. Habe es nun ebenfalls über Github geladen - funktioniert jetzt auch bei mir...

**Comment by DanielWeitenauer** [comment]
Die neue Version 1.3.0 ist nun auch im Installer.
