### ISSUE TITLE
Meta-Infos standardmäßig ausgeblendet

### ISSUE THREAD

**Issue by F-L-O-R-I-A-N-S** [FriendsOfREDAXO/structure_tweaks#75]
Hallo zusammen,
leider bin ich neulich über die Funktion gestolpert, dass Metainfos standardmäßig ausgeblendet werden, wenn nicht explizit angeklickt wird, dass diese sichtbar sein sollen.
Ich schlage daher vor, dass die Metainfos grundsätzlich eingeblendet sind und auf Wunsch ausgeblendet werden können, also umgekehrt wie bisher.

Viele Grüße

**Comment by DanielWeitenauer** [comment]
Kannst du das genauer erklären? Welche Funktion meinst du?

**Comment by F-L-O-R-I-A-N-S** [comment]
Es gibt in den Einstellungen von Structure Tweaks die Möglichkeit "Metainfos einblenden?" (genauer Wortlaut möglicherweise anders, habe gerade keine Installation zum Nachgucken zur Hand). Wenn man das Häkchen nicht aktiviert, sind die Metainfos ausgeblendet.
Klüger wäre es, wenn man sagen könnte, dass die Metainfos ausgeblendet werden können und nicht, dass man diese explizit einblenden muss.

**Comment by DanielWeitenauer** [comment]
Ich verstehe jetzt was du meinst. Diese Funktion kehrt eine Änderung um, die vor einiger Zeit in den REDAXO-Core eingebunden wurde: die Metadaten sind in REDAXO 5.10 vom Tab in die Seitenleiste des Artikels verschoben worden, also nicht wirklich ausgebelendet. Das Häkchen macht die Änderung rückgängig. 
Daher ist das Verhalten so schon korrekt: ohne Häkchen Standardverhalten des Cores, mit Häkchen das vom Addon veränderte.

**Comment by F-L-O-R-I-A-N-S** [comment]
Ich hatte in der Redaxo-Installation, die ich verwendet habe, das Problem, dass die Meta-Informationen komplett verschwunden waren. Das Core-Update wurde also nicht, wie von dir beschrieben, rückgängig gemacht, sondern hat die Meta-Informationen komplett verschluckt.
Siehe Screenshot hier: https://ibb.co/Vv3rxxk

**Comment by DanielWeitenauer** [comment]
Wir haben es lösen können: 
Da sich in REDAXO 5.10 und structure_tweaks 1.2 die Funktionalität umgekehrt hat, gibt es Ausgabeprobleme, wenn nicht die zueinander passenden Versionen installiert sind (siehe dazu auch hier https://github.com/redaxo/redaxo/pull/3337#pullrequestreview-363319206 und hier https://github.com/FriendsOfREDAXO/structure_tweaks/issues/60)  
**Daher für REDAXO > 5.10 immer structure_tweaks > 1.2 verwenden.** Für ältere REDAXO-Versionen ist structure_tweaks > 1.2 abwärtskompatibel.
