### ISSUE TITLE
Whoops mit Redaxo 5.12.0

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/structure_tweaks#76]
Structure Tweaks 1.30 @ Redaxo 5.12.0 - Ich möchte die Funktion "Metainfos in eigenem Tab" nutzen und sobald ich das aktiviere whoopt es dann sobald ich in der Artikelansicht den Tab anklicke. Kann das jemand reproduzieren? Bilder im Thread. Außerdem kommt es dann auch zu einem Umlautefehler in der Artikelansicht...

<img width="1955" alt="Bildschirmfoto 2021-03-12 um 10 37 41" src="https://user-images.githubusercontent.com/10958385/110926581-dd4ffc00-8324-11eb-96b6-f461b7ff1aaa.png">
<img width="390" alt="Bildschirmfoto 2021-03-12 um 10 40 36" src="https://user-images.githubusercontent.com/10958385/110926584-dfb25600-8324-11eb-8db2-79e7814ea5ee.png">

**Comment by DanielWeitenauer** [comment]
Es sieht auf den ersten Blick so aus, dass es an diesem Commit liegt: https://github.com/redaxo/redaxo/pull/4464 structure_tweaks übernimmt bisher gesetzte Variablen ohne Prüfung. Theoretisch sollte es genügen in content.metainfo.php den Variablennamen $article_id auf $articleId zu ändern. Ich würde das jedoch am WE nochmal genauer anschauen und versuchen eine robustere Lösung zu finden.

**Comment by dpf-dd** [comment]
Danke für den schnellen Fix - das funktioniert. Allerdings zerschießt es die Umlaute in der Metainfo-Box der Artikelansicht immernoch. Aber das ist mir erstmal egal weil rein kosmetisch. Mir hilft es erstmal wieder in den Tab zu kommen. Vielen Dank!

**Comment by DanielWeitenauer** [comment]
Neue Version 1.3.1 - Die Variablenwerte werden nun aus der URL übernommen: 7ae15cf6f0e614f884291297659add3e9c1b382c 
Den Fehler mit den Umlauten kann ich nicht nachvollziehen, bei mir werden sie in allen Installationen korrekt ausgegeben. Evtl. gibt es bei dir ein Problem mit der Kodierung. Kannst du mal deine DB-Kodierung prüfen?
Für das Icon gerne eine neue Issue aufmachen.

**Comment by DanielWeitenauer** [comment]
Ich habe de Fehler gefunden und behoben: 4c5f12c287294b8e22be3b809ddf28daccc4eec8

Für das Icon kannst du gerne eine neue Issue aufmachen.
